### ISSUE TITLE
Colab alphafold error

### ISSUE THREAD

**Issue by TBlower** [deepmind/alphafold#127] opened 2021-08-13 08:43 UTC
Hi Alphafold Team. First of all, congratulations and thank you for producing and sharing this impressive and very useful tool. We have been eagerly engaging with the outputs and it will no doubt speed up progress in many ways. I have been using the colab workflow every day for the last ten days going through our target proteins. I haven't done anything differently for the last two days, but when I get to step 4, "search against genetic databases", there is an error. I do not have enough expertise to diagnose the problem, and I was hoping you might guide me, please? I have upgraded to "colab pro" so I'm not sure that it would be data usage etc. Thank you in advance for your help. Best wishes, Tim. Here's the error output:

---------------------------------------------------------------------------

NotFoundError                             Traceback (most recent call last)

<ipython-input-4-1640ae7ce3a3> in <module>()
     24 import py3Dmol
     25 
---> 26 from alphafold.model import model
     27 from alphafold.model import config
     28 from alphafold.model import data

6 frames

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/load_library.py in load_library(library_location)
    152 
    153     for lib in kernel_libraries:
--> 154       py_tf.TF_LoadLibrary(lib)
    155 
    156   else:

NotFoundError: /opt/conda/lib/python3.7/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl12lts_2021032411string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS9_EE

**Comment by Augustin-Zidek** [comment] 2021-08-13 08:58
Sorry about this, this was caused by the recent TF update. The solution is to change the line:

```
%shell pip3 install ./alphafold
```

in the Download AlphaFold cell to
```
# Install the required versions of all dependencies.
%shell pip3 install -r ./alphafold/requirements.txt
# Run setup.py to install only AlphaFold.
%shell pip3 install --no-dependencies ./alphafold
```

I will push a fix for this as soon as possible.

Closing this issue as a duplicate of #124 where I will tract future updates.

**Closed by Augustin-Zidek** 2021-08-13 08:58 UTC

**Comment by TBlower** [comment] 2021-08-13 09:20
Fab - thank you so much for the rapid response!!

**Comment by gustheman** [comment] 2021-08-16 18:20
I just tried the colab with the suggested changes (it's already changed in the colab) but I'm still getting the same error.
am I missing anything?

**Comment by KristinaGagalova** [comment] 2021-08-23 22:04
Hi, 
I am also having the same error even if the changes. Do you have any suggestions on how to fix that?

**Comment by AnyaP** [comment] 2021-08-24 18:01
Hi, sorry about this. We are submitting a new fix soon, but meanwhile you could try to apply it manually by running 

`!pip uninstall -y tensorflow`

before all other cells of the notebook. This will uninstall TensorFlow 2.6.0, which is now provided by default in the Colab and which is conflicting with AF dependencies.

**Comment by AnyaP** [comment] 2021-08-24 18:10
I will post future updates on the newer issue #148, which reports the same error.

**Comment by Leon-HXL** [comment] 2021-08-25 02:21
> Hi, sorry about this. We are submitting a new fix soon, but meanwhile you could try to apply it manually by running
> 
> `!pip uninstall -y tensorflow`
> 
> before all other cells of the notebook. This will uninstall TensorFlow 2.6.0, which is now provided by default in the Colab and which is conflicting with AF dependencies.

I just tried it, but it is not working. The same error shows up.

**Comment by KristinaGagalova** [comment] 2021-08-25 03:00
Thank you for the fast reply, it works fine
