### ISSUE TITLE
ModuleNotFoundError 

### ISSUE THREAD

**Issue by rubindg** [deepmind/alphafold#45] opened 2021-07-23 11:11 UTC
I am running colab module of alphafold but it gives me the following error although I have followed the steps. I ran it once on one of the protein and it worked but now it seems to not find the module. I hope you can help.

Regards,
Rubin.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-18-1640ae7ce3a3> in <module>()
     24 import py3Dmol
     25 
---> 26 from alphafold.model import model
     27 from alphafold.model import config
     28 from alphafold.model import data

ModuleNotFoundError: No module named 'alphafold.model'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by abridgland** [comment] 2021-07-23 11:51
Hi, thanks for reporting this. It sounds like you might need to run the second cell, named "Download AlphaFold". If you've tried that and you still get this issue then please let me know any steps I can take to reproduce the problem! In the meantime you can always restart the Colab runtime by going to Runtime > Factory reset runtime in the toolbar. Then you will be able to rerun the first two cells to set up AlphaFold from scratch. It’s only a workaround but I hope it should get things working for you again.

**Comment by rubindg** [comment] 2021-07-23 12:06
Thank you for the suggestions. I could fix it after Factory reset runtime. After every run I have to reset factory setting and it works.

**Comment by Nisha20591** [comment] 2021-07-24 07:38
Hi,

I have a similar error. I have tried both "Download Alphafold" which results in the error and I have tried the factory reset option. It doesn't seem to rectify the issue. Any suggestions?

Thanks, 

Nisha

**Comment by Augustin-Zidek** [comment] 2021-08-03 09:43
We had some missing `__init__.py` files, but this is now fixed. Are you still seeing this issue?

**Comment by Augustin-Zidek** [comment] 2021-08-03 10:48
Could you also try the following two methods:

**Method 1**
1. Run the "Install third-party software" cell. 
2. Restart Runtime. 
3. Then run your import statement cell.

**Method 2**
If Method 1 doesn't help, then try rerunning the "Install third-party software" but change the line

```
%shell pip install py3dmol
```

to

```
%shell pip install -e py3dmol 
```

See also more tips in https://stackoverflow.com/questions/57838013/modulenotfounderror-after-successful-pip-install-in-google-colaboratory.

**Closed** 2021-08-09 11:11 UTC

**Comment by Augustin-Zidek** [comment] 2021-08-09 11:13
Closing this issue now as this seems to be a transient Colab problem, see also the discussion in https://github.com/deepmind/alphafold/issues/47. Feel free to re-open if my workaround above doesn't work.
