### ISSUE TITLE
Not found error in search against genetic databases

### ISSUE THREAD

**Issue by rezwansidd93** [deepmind/alphafold#125] opened 2021-08-13 00:26 UTC
![image](https://user-images.githubusercontent.com/88864103/129286370-53940dad-aacc-46e6-9818-e644cb776402.png)

**Comment by Augustin-Zidek** [comment] 2021-08-13 07:21
This is also duplicate of #124 – I will close this issue and continue the discussion in #124.

**Closed by Augustin-Zidek** 2021-08-13 07:21 UTC
