### ISSUE TITLE
jax.tree_util.tree_multimap() is deprecated

### ISSUE THREAD

**Issue by MWNautilus** [deepmind/alphafold#456] opened 2022-05-05 08:46 UTC
I got the follwoing messenge in cell 5 (run alphafold & relax with AMBER):

/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py:189: FutureWarning: jax.tree_util.tree_multimap() is deprecated. Please use jax.tree_util.tree_map() instead as a drop-in replacement.
  'instead as a drop-in replacement.', FutureWarning)

Any idea what exactly the issue is?
-Michael.

**Comment by polinanvkv** [comment] 2022-05-05 13:58
I've got the same issue.

**Comment by watso141** [comment] 2022-05-19 17:27
I also have the same issue, help welcome!

**Comment by tfgg** [comment] 2022-05-19 18:38
Hi, this is just a warning message - you can safely ignore it. We'll fix it (by moving to `tree_map`) at some point.

**Comment by watso141** [comment] 2022-05-20 17:34
Thank you for getting back to me so fast! Ok that's good info, for some
reason the run still halts every time I try to run the Collab notebook,
usually very close to it finishing section 5. Here is a screenshot of the
run I just tried to complete, please let me know if there is anything I can
do to help or anything I am doing incorrectly. Thanks!

[image: image.png]

**Comment by Joey305** [comment] 2022-05-20 22:24
![AF Error](https://user-images.githubusercontent.com/95382881/169619851-877058cc-e3b8-4477-b6fd-2ac54cfa625f.JPG)
I am trying to run a prediction and get this same error and the message that minimization timed out. I am not sure what i am doing wrong or if i am doing anything wrong in the first place. Can someone assist me with this issue? It has been happening to me the past 24 hours and it usually occurs when it is on its last relaxation which makes it all the more frustrating. 

Any assistance is appreciated.
Joey

**Comment by Joey305** [comment] 2022-05-20 23:57
![image](https://user-images.githubusercontent.com/95382881/169625764-232596c2-3efe-4963-a08f-ec28232f1e97.png)
This is the new error message i am getting. I do not know what the issue is but i would appreciate some assistance with getting AlphaFold to work properly.

**Comment by watso141** [comment] 2022-05-23 15:25
I was able to complete my run without relaxation, still not sure what is preventing the colab notebook from doing the relaxation step, hopefully someone knowledgeable gets a chance to look at the screenshots above

**Comment by AngieSanchez** [comment] 2022-05-23 22:45
> 

Hi @Joey305, I get the same error, first, it was the error about the relaxation, I defined run_relax = False and it solved that problem, however now I get the error of "A UTF-8 locale is required. Got ANSI_X3.4-1968". Have you been able to solve that error? Can you help me with this issue?

**Comment by Joey305** [comment] 2022-05-23 22:50
Hi Angie, you caught me just as i was about to wrap up my day so i am glad i am able to respond promptly. I have not been able to solve this issue, even when i run the prediction from 3 different computers using different sequences. I originally thought it was an issue with my sequences but when i ran predictions i had previously done and got this same error, i knew it was not a me issue and that (from my deep dive into googling this issue) that for some reason the back end of the software isn't connecting to the drivers that it needs to connect and it is kicking out the predictions right before they finish. I am thinking it might be a ploy by DeepMind/Google to get us to subscribe to Collab Pro because i am sure that it will most likely magically fix my issues if i pay for the service instead of using it for free! Just my two cents at least, whatever its good for!

**Comment by AngieSanchez** [comment] 2022-05-23 22:59
> 
Umm Ok, Thank you anyway. I will let you know if I can solve it.

**Comment by cheesio-lab** [comment] 2022-05-25 09:50
i have the same problem...unfortunately the analysis seems to be interrupted shortly before finishing and everything is gone. Do you know how to fix this?
![Bildschirmfoto 2022-05-24 um 12 53 46](https://user-images.githubusercontent.com/106238101/170234688-9ce4dc97-0622-435f-b0c9-929817a0db30.png)
![Bildschirmfoto 2022-05-24 um 10 34 30](https://user-images.githubusercontent.com/106238101/170234702-e332c051-52e2-43da-8508-0b10e62fadaa.png)

**Comment by cheesio-lab** [comment] 2022-05-25 13:24
also this always occurs... can anybody help me?

![Bildschirmfoto 2022-05-25 um 15 22 56](https://user-images.githubusercontent.com/106238101/170272623-6d9a188e-acfc-4603-b84e-bbf48f1a0ec2.png)

**Comment by Htomlinson14** [comment] 2022-08-19 13:45
Hi thanks for raising this issue! This duplicates a few issues such as https://github.com/deepmind/alphafold/issues/483 and https://github.com/deepmind/alphafold/issues/383 so closing this issue

**Closed by Htomlinson14** 2022-08-19 13:45 UTC
Labels: duplicate

**Comment by MasterNivek** [comment] 2022-12-05 08:50
any one can tell me how to fix this please 
![image](https://user-images.githubusercontent.com/108690998/205593972-a52d230b-3592-461b-88f0-6436b90bb520.png)

**Comment by jinmingyi1998** [comment] 2022-12-13 09:18
solved in #630  just replace all tree_utils. becacuse jax moved them.
