### ISSUE TITLE
TypeError: load_config() got an unexpected keyword argument 'config_dict'

### ISSUE THREAD

**Issue by rudegans** [deepmind/alphafold#426] opened 2022-04-08 02:29 UTC
```
$ python3 docker/run_docker.py --fasta_paths=/home/qianlei/AF2/alphafold-main/example/1pazA.fasta --max_template_date=2020-05-14 --data_dir=/data/alphafold2_database/af2_database/sp3d_data/path/to/download/directory/
I0407 09:31:06.469204 139628945311552 run_docker.py:115] Mounting /home/qianlei/AF2/alphafold-main/example -> /mnt/fasta_path_0
I0407 09:31:06.469478 139628945311552 run_docker.py:115] Mounting /data/alphafold2_database/af2_database/sp3d_data/path/to/download/directory/uniref90 -> /mnt/uniref90_database_path
I0407 09:31:06.469695 139628945311552 run_docker.py:115] Mounting /data/alphafold2_database/af2_database/sp3d_data/path/to/download/directory/mgnify -> /mnt/mgnify_database_path
I0407 09:31:06.469836 139628945311552 run_docker.py:115] Mounting /data/alphafold2_database/af2_database/sp3d_data/path/to/download/directory -> /mnt/data_dir
I0407 09:31:06.469969 139628945311552 run_docker.py:115] Mounting /data/alphafold2_database/af2_database/sp3d_data/path/to/download/directory/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0407 09:31:06.470114 139628945311552 run_docker.py:115] Mounting /data/alphafold2_database/af2_database/sp3d_data/path/to/download/directory/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0407 09:31:06.470263 139628945311552 run_docker.py:115] Mounting /data/alphafold2_database/af2_database/sp3d_data/path/to/download/directory/pdb70 -> /mnt/pdb70_database_path
I0407 09:31:06.470412 139628945311552 run_docker.py:115] Mounting /data/alphafold2_database/af2_database/sp3d_data/path/to/download/directory/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0407 09:31:06.470563 139628945311552 run_docker.py:115] Mounting /data/alphafold2_database/af2_database/sp3d_data/path/to/download/directory/bfd -> /mnt/bfd_database_path
Traceback (most recent call last):
  File "docker/run_docker.py", line 266, in <module>
    app.run(main)
  File "/opt/python-3.6.8/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/python-3.6.8/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "docker/run_docker.py", line 231, in main
    client = docker.from_env()
  File "/opt/python-3.6.8/lib/python3.6/site-packages/docker/client.py", line 101, in from_env
    **kwargs_from_env(**kwargs)
  File "/opt/python-3.6.8/lib/python3.6/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/opt/python-3.6.8/lib/python3.6/site-packages/docker/api/client.py", line 132, in __init__
    config_dict=self._general_configs, credstore_env=credstore_env,
TypeError: load_config() got an unexpected keyword argument 'config_dict'
```

**Comment by guleng** [comment] 2022-05-11 04:09
@rudegans I also encountered a similar problem. Has this problem been solved？

**Comment by Augustin-Zidek** [comment] 2022-08-19 13:53
Hi, we are unable to reproduce this issue. Is it still a problem?

**Comment by Augustin-Zidek** [comment] 2023-01-16 15:16
Closing this issue, feel free to reopen this issue or open a new issue if this is still a problem.

**Closed by Augustin-Zidek** 2023-01-16 15:16 UTC
