### ISSUE TITLE
RuntimeError: HHblits failed

### ISSUE THREAD

**Issue by LuGarfield** [deepmind/alphafold#73] opened 2021-07-29 07:48 UTC
![image](https://user-images.githubusercontent.com/4409715/127452301-4bed6b5b-e799-402b-9e18-2c4575003281.png)

I can run alphafold, but everytime it  fails at   line 144 in  hhblits.py. 
Does anyone face this situation?
Thank you!

**Comment by akhoroshev** [comment] 2021-07-29 07:59
I have the same error

**Comment by LuGarfield** [comment] 2021-07-29 08:31
I don't know why this error happens,  could anyone find the reason? thanks!

**Comment by akhoroshev** [comment] 2021-07-29 08:45
> I don't know why this error happens, could anyone find the reason? thanks!

Alphafold worked for me when I used this this PR fix: https://github.com/deepmind/alphafold/pull/36

But when I use the last master commit https://github.com/deepmind/alphafold/tree/1e216f93f06aa04aa699562f504db1d02c3b704c

I have the error above

**Comment by chrisroat** [comment] 2021-07-29 21:58
When I try and build the docker file (trying my best to use consistent versions of software), I always see warnings in the compilation of hhblits.  The warnings vary depending the base version of ubuntu used, because each version uses a different default compiler version. 

FWIW, I see the fewest compilation warnings using ubuntu 16.04, which is the version currently in the repo's Dockerfile.  (Note that it is currently passed end-of-life and is no longer supported.)  My PR #36 used 20.04, which does display more warnings.

This is not to say the warnings are a problem.  Just an observation that you may get different behavior using different compilers, especially if there is some memory related problem.

**Comment by akhoroshev** [comment] 2021-07-30 06:13
> When I try and build the docker file (trying my best to use consistent versions of software), I always see warnings in the compilation of hhblits. The warnings vary depending the base version of ubuntu used, because each version uses a different default compiler version.
> 
> FWIW, I see the fewest compilation warnings using ubuntu 16.04, which is the version currently in the repo's Dockerfile. (Note that it is currently passed end-of-life and is no longer supported.) My PR #36 used 20.04, which does display more warnings.
> 
> This is not to say the warnings are a problem. Just an observation that you may get different behavior using different compilers, especially if there is some memory related problem.

Hmmmm interesting.

In nvidia/cuda:11.0-cudnn8-runtime-ubuntu16.04 image after installing the build-essential i have
```
root@822f34c25aaf:/# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
```

In nvidia/cuda:11.0-cudnn8-runtime-ubuntu18.04 image after installing the build-essential I have
```
root@e7ecd162bf99:/# gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

And the last image seems to work with the hhblits for me.

@LuGarfield can you change base image from `nvidia/cuda:${CUDA}-cudnn8-runtime-ubuntu16.04` to `nvidia/cuda:${CUDA}-cudnn8-runtime-ubuntu18.04` and check the pipeline again?

**Comment by LuGarfield** [comment] 2021-07-30 08:38
> When I try and build the docker file (trying my best to use consistent versions of software), I always see warnings in the compilation of hhblits. The warnings vary depending the base version of ubuntu used, because each version uses a different default compiler version.
> 
> FWIW, I see the fewest compilation warnings using ubuntu 16.04, which is the version currently in the repo's Dockerfile. (Note that it is currently passed end-of-life and is no longer supported.) My PR #36 used 20.04, which does display more warnings.
> 
> This is not to say the warnings are a problem. Just an observation that you may get different behavior using different compilers, especially if there is some memory related problem.

i found these  warnings  when i compile docker env. 

![image](https://user-images.githubusercontent.com/4409715/127625775-b0661e2c-7590-429e-9b15-fde0144984a3.png)

![image](https://user-images.githubusercontent.com/4409715/127626011-4dcfd0e8-4684-460a-b3a4-6df70d5736f6.png)

![image](https://user-images.githubusercontent.com/4409715/127626060-6c4ef3a8-2781-4896-94b0-e3df509416e0.png)

![image](https://user-images.githubusercontent.com/4409715/127626085-ee35b1a5-5613-4d8c-ad77-8e9f62893281.png)

**Comment by LuGarfield** [comment] 2021-07-30 09:08
> > When I try and build the docker file (trying my best to use consistent versions of software), I always see warnings in the compilation of hhblits. The warnings vary depending the base version of ubuntu used, because each version uses a different default compiler version.
> > FWIW, I see the fewest compilation warnings using ubuntu 16.04, which is the version currently in the repo's Dockerfile. (Note that it is currently passed end-of-life and is no longer supported.) My PR #36 used 20.04, which does display more warnings.
> > This is not to say the warnings are a problem. Just an observation that you may get different behavior using different compilers, especially if there is some memory related problem.
> 
> Hmmmm interesting.
> 
> In nvidia/cuda:11.0-cudnn8-runtime-ubuntu16.04 image after installing the build-essential i have
> 
> ```
> root@822f34c25aaf:/# gcc --version
> gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
> ```
> 
> In nvidia/cuda:11.0-cudnn8-runtime-ubuntu18.04 image after installing the build-essential I have
> 
> ```
> root@e7ecd162bf99:/# gcc --version
> gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> ```
> 
> And the last image seems to work with the hhblits for me.
> 
> @LuGarfield can you change base image from `nvidia/cuda:${CUDA}-cudnn8-runtime-ubuntu16.04` to `nvidia/cuda:${CUDA}-cudnn8-runtime-ubuntu18.04` and check the pipeline again?

@akhoroshev 
my settings : 
ARG CUDA_FULL=11.2.2
FROM nvidia/cuda:${CUDA_FULL}-cudnn8-runtime-ubuntu20.04

![image](https://user-images.githubusercontent.com/4409715/127628279-2826a5f5-b03a-4231-92d9-98e1d210066d.png)

still have the problem

**Comment by dypp1013** [comment] 2021-07-31 15:02
I met the same error. And notably, this happened when I submitted protein sequence longer than 1k AA. Protein smaller than 1k AA  could be calculated normally. So I suspected if the memory space for HHblits is matters.

**Comment by martinbonin** [comment] 2021-08-03 12:19
Does anyone mange to solve this problem? I got the same red errors as posted by @LuGarfield and also the same initial error. So far I was not able to fix it. My protein is far below 1k AA, but I have only 16GB RAM. Could this be a problem?

**Comment by Zuricho** [comment] 2021-08-03 15:00
Did you have the "segmentation fault" ?
I have met this error (and I have segmentation fault" when I only use ONE cpu for MSA. I solved this problem by give the it more CPUs and memory and it worked. After that, some friends occasionally asked me about this question and I usually suggesting them to add more CPUs. Because our HPC cluster only give maximum 6 CPUs for 1 GPU, so I let them use more GPU cards to have more CPUs, which means more memory.

**Comment by martinbonin** [comment] 2021-08-03 15:42
I don't get a segmentation fault. So far I'm running it on my own computer and I used my NAS to store all the databases. I have a Intel® Core™ i9-9980HK CPU @ 2.40GHz × 16, a NVIDIA GeForce GTX 1650/PCIe/SSE2 and 16 GB of RAM. Could this be insufficient to run AlphaFold?

**Comment by Lsz-20** [comment] 2021-12-06 02:42
Hello, it seems same question~when i run multimer it show me this,but it works well when i run monomer.
Here are the errors:

![QQ图片20211205232246](https://user-images.githubusercontent.com/60343452/144778497-f20ab58b-8158-4be3-b410-f310d4953d52.jpg)
If you have any ideas?Thanks!

**Comment by Augustin-Zidek** [comment] 2021-12-16 14:53
This may be caused by insufficient RAM – if you are using less than 32 GB RAM then upgrading your RAM to 32 GB will probably solve the issue.

Another complete workaround for this is to run with `--db_preset=reduced_dbs` as specified in the README. This uses a different tool (jackhmmer) for the genetic search. Closing this issue for now, feel free to reopen if this is still a problem.

**Closed by Augustin-Zidek** 2021-12-16 14:53 UTC
Labels: error report, third-party tool

**Comment by Lsz-20** [comment] 2021-12-17 08:54
> This may be caused by insufficient RAM – if you are using less than 32 GB RAM then upgrading your RAM to 32 GB will probably solve the issue.
> 
> Another complete workaround for this is to run with `--db_preset=reduced_dbs` as specified in the README. This uses a different tool (jackhmmer) for the genetic search. Closing this issue for now, feel free to reopen if this is still a problem.

Ok,thanks for your help
