### ISSUE TITLE
Alphafold exits without result, but with warning of maximum number of residues 32763 exceeded in sequence

### ISSUE THREAD

**Issue by qingsongli1979** [deepmind/alphafold#135] opened 2021-08-18 09:30 UTC
Alphafold exists without result, but reamins lots of warnings such as below:

I0818 04:41:49.407580 47894079450816 run_docker-2.py:193] E0817 20:41:49.119690 140014160611136 hhblits.py:141] - 19:20:25.909 WARNING: maximum number of residues 32763 exceeded in sequence tr|A0A091T648|A0A091T648_PHALP Titin (Fragment) OS=Phaethon lepturus GN=N335_02550 PE=4 SV=1

Anyone knows what it is about?

**Comment by rainwala** [comment] 2021-09-03 14:36
I have the same problem.

**Comment by ValZapod** [comment] 2021-09-24 16:07
> Titin

This is from ChimeraX twitter? They did not use the full sequence. They cut in pieces.

**Comment by Augustin-Zidek** [comment] 2021-09-24 16:17
Duplicate of https://github.com/deepmind/alphafold/issues/172. 

TL;DR: AlphaFold can fold at most 2,700-residue proteins and the sequence you are trying to run with is 32k residues. The best workaround is to split the sequence in shorter ones and fold those, then merge.

**Closed by Augustin-Zidek** 2021-09-24 16:17 UTC
Labels: error report, third-party tool

**Comment by ValZapod** [comment] 2021-09-27 19:01
> AlphaFold can fold at most 2,700-residue proteins and the sequence you are trying to run with is 32k residues. The best workaround is to split the sequence in shorter ones

Actually what Alphafold DB does it splits into highly overlapping segments of 1400aa length overlapping fragments (residues 1–1400, residues 201–1600, etc).

**Comment by nanomolar** [comment] 2023-04-13 07:53
I got the same problem for a complex sequence with 200 residues. Could anyone provide answers?

**Comment by noah-c-noah-do** [comment] 2023-06-07 13:59
> I got the same problem for a complex sequence with 200 residues. Could anyone provide answers?

I also got this issue on a multimer run with sequences of 200-400. I believe the issue is that Titin proteins are being found as templates/homologs b and their size is causing the issue

**Comment by cedarice** [comment] 2023-06-13 08:55
I have the same problem, too!

**Comment by tcoates5** [comment] 2023-06-13 14:10
I am seeing a similar problem

**Comment by javierbq** [comment] 2023-07-09 05:10
Same problem
