### ISSUE TITLE
Installing 3rd party software on Colab not working

### ISSUE THREAD

**Issue by quockerwodger** [deepmind/alphafold#533] opened 2022-07-13 23:35 UTC
Hello there!

When I run the first module on the colab notebook to install third party software, it almost immediately fails and comes up with this error message. I'm not sure if this is something I can fix myself or not, I'm not very knowledgeable with any form of coding.

WARNING: Skipping tensorflow as it is not installed.
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 

```
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-4-97d4183e8ad4>](https://localhost:8080/#) in <module>()
     21       get_ipython().magic('shell pip uninstall -y tensorflow')
     22 
---> 23       get_ipython().magic('shell sudo apt install --quiet --yes hmmer')
     24       pbar.update(6)
     25 

3 frames
[/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    137     if self.returncode:
    138       raise subprocess.CalledProcessError(
--> 139           returncode=self.returncode, cmd=self.args, output=self.output)
    140 
    141   def _repr_pretty_(self, p, cycle):  # pylint:disable=unused-argument

CalledProcessError: Command 'sudo apt install --quiet --yes hmmer' returned non-zero exit status 100.
```

**Comment by Augustin-Zidek** [comment] 2023-01-17 08:57
Is this still an issue? I can't reproduce this unfortunately.

**Comment by Augustin-Zidek** [comment] 2023-02-08 15:35
Closing this issue now, feel free to re-open if there is anything we could help with.

**Closed by Augustin-Zidek** 2023-02-08 15:35 UTC
Labels: colab
