### ISSUE TITLE
a question about search template

### ISSUE THREAD

**Issue by Pharmacy-student** [deepmind/alphafold#501] opened 2022-06-10 05:44 UTC
Dear AlphaFold authors,

 I am going to use ALPHAFOLD to predict a protein 7V1R.fasta that is already structured in PDB. But I found that 7v1r template is not used in prediction. I changed a bit of the sequence on the 7V1R, and it's not used either. I can find 7v1r.cif in mmcif. The structure upload time of 7v1r is 2021, I have made max_template_date=2022-06-01.
 I thought it would use the model most similar to the predicted sequence, but that doesn't seem to be the case. The same happened when I predicted 6XNB.fasta. But when I go to predict 6AHE.fasta, it uses 6ahe template.
Why is this, if I want to use these templates, what should I do?

Regards,
Kevin

**Comment by Augustin-Zidek** [comment] 2022-08-19 13:35
Duplicate of https://github.com/deepmind/alphafold/issues/190.

**Closed by Augustin-Zidek** 2022-08-19 13:35 UTC
