### ISSUE TITLE
Download/Setup: FTP to HTTPS

### ISSUE THREAD

**Issue by Faezov** [deepmind/alphafold#774] opened 2023-05-31 20:34 UTC
Hello Developers,

It would be nice if you replace in scripts folder "ftp://" to "https://", links are unusable as is

With best,
Bulat

**Comment by Augustin-Zidek** [comment] 2023-06-01 12:37
Sure, fixed in https://github.com/deepmind/alphafold/commit/4bd3ff76cc51613af617f49e8179b603ee2f1576.

Note that the FTP links work for me so this is likely to be caused by your network/firewall.

**Closed by Augustin-Zidek** 2023-06-01 12:37 UTC
