### ISSUE TITLE
docker build

### ISSUE THREAD

**Issue by jianhaoc** [deepmind/alphafold#104] opened 2021-08-08 03:21 UTC
Hi,

I tried to install alphafold in CentOS7 (3.10.0-1127.el7.x86_64) and ran "$ docker build -f docker/Dockerfile -t alphafold ." according to guide and see procedure went very slowly (see below).
Sending build context to Docker daemon  2.557TB

I checked / is fully occupied (see below).
/dev/sda5       244G  244G   20K 100% /

How much space is required for docker build and how can I avoid / is fully occupied? Should I change anything in setting?

Thank you!
Jianhao

**Comment by chrisroat** [comment] 2021-08-08 04:53
The problem is that your command is sending 2.5TB of data to docker.  The docker build context is everything in the subdirectory below "." (the current directory) in your command (except for paths matching lines in a potential .dockerignore file).  

Based on the size, this might be all the genetic databases and model parameters.    Whatever it is, you should move it out of your repo and put it somewhere else.

**Comment by jianhaoc** [comment] 2021-08-08 06:10
When docker build is almost done. There is an error below:
Error response from daemon: Error processing tar file(exit status 1): write /d/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffdata: no space left on device

However, while I checked current storage space, there is still 6.1T available. So I'm confused. Does the docker build use any other storage space? My workstation has 256G memory.

**Comment by chrisroat** [comment] 2021-08-09 18:18
You still have your downloaded databases in your docker context.  Basically, docker is trying to copy all the databases onto your image (because they are inside your cloned repo), which is not how things are intended to work. 

You should move the bfd directory (and any other databases you have) out of your repo.

**Comment by ctmckee** [comment] 2021-08-09 23:46
Just experienced same issue.  Would be good to document a demo directory structure.

**Comment by andycowie** [comment] 2021-12-16 15:50
This issue was addressed in [0be2b30](https://github.com/deepmind/alphafold/commit/0be2b30b98f0da7aecb973bde04758fae67eb913).

Thanks to jamespeapen for the suggestion.

**Closed by andycowie** 2021-12-16 15:50 UTC
Labels: setup
