### ISSUE TITLE
undefined symbol in "Search against genetic databases"

### ISSUE THREAD

**Issue by Zhaleh2** [deepmind/alphafold#124] opened 2021-08-12 22:32 UTC
I am getting this error while running the sample amino acid sequence:
NotFoundError: /opt/conda/lib/python3.7/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl12lts_2021032411string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS9_EE
![bug](https://user-images.githubusercontent.com/38191812/129278159-ca490915-4ce9-414e-9a33-f01272d4d0cc.jpg)

btw, I am running the AF2 Colab: https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb
Thanks, Zhaleh

**Comment by Augustin-Zidek** [comment] 2021-08-13 07:20
Sorry about this, this was caused by the recent TF update. The solution is to change the line:

```
%shell pip3 install ./alphafold
```

in the *Download AlphaFold* cell to

```
# Install the required versions of all dependencies.
%shell pip3 install -r ./alphafold/requirements.txt
# Run setup.py to install only AlphaFold.
%shell pip3 install --no-dependencies ./alphafold
```

I will push a fix for this as soon as possible.

**Comment by TBlower** [comment] 2021-08-13 09:21
Thanks for the fix!

**Comment by Augustin-Zidek** [comment] 2021-08-13 09:58
Fixed in https://github.com/deepmind/alphafold/commit/f65e94fc71093caf4243643022eac30a449c6f7c.

**Closed by Augustin-Zidek** 2021-08-13 09:58 UTC

**Comment by Zhaleh2** [comment] 2021-08-13 15:26
Thank you all for your prompt replies!
