### ISSUE TITLE
AlphaFold multimer has import error in Step 5

### ISSUE THREAD

**Issue by Isabel-ql** [deepmind/alphafold#649] opened 2022-12-02 11:32 UTC
Hi, 

I tried to predict structures of complexes with AlphaFold Multimer using the link: https://colab.research.google.com/drive/1J1G8OC6LZwT6Tqdz4uLRmnVzj7WWgUg1?usp=sharinga 

It worked well before, but a problem appeared yesterday. In step 5, "Search against genetic database", there's an import error (See below). I tried with different browsers, the problem still exists.

Is anybody know how to fix the problem? Thanks very much!

Cheers,
Qun

<img width="1381" alt="AlphaFold Multimer_step5" src="https://user-images.githubusercontent.com/65905482/205283476-bb018f25-61b6-4391-8a66-022dc90acce7.png">

**Comment by Htomlinson14** [comment] 2022-12-02 14:31
Hi thanks for raising this. Its a duplicate of https://github.com/deepmind/alphafold/issues/648 so closing

**Closed** 2022-12-02 14:56 UTC
Labels: duplicate
