### ISSUE TITLE
Problem dowloading results

### ISSUE THREAD

**Issue by almeida85** [deepmind/alphafold#509] opened 2022-06-15 15:26 UTC
Hello,

I ran AlphaFold-Multimers Colab ([https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb](url)) but the results cannot be downloaded. Below is the error:

```
NotImplementedError                       Traceback (most recent call last)

[<ipython-input-8-e612fd4aa5be>](https://localhost:8080/#) in <module>()
    210 
    211 # --- Download the predictions ---
--> 212 get_ipython().system('zip -q -r {output_dir}.zip {output_dir}')
    213 files.download(f'{output_dir}.zip')

2 frames

[/usr/local/lib/python3.7/dist-packages/google/colab/_shell.py](https://localhost:8080/#) in system(self, *args, **kwargs)
    100       kwargs.update({'also_return_output': True})
    101 
--> 102     output = _system_commands._system_compat(self, *args, **kwargs)  # pylint:disable=protected-access
    103 
    104     if pip_warn:

[/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in _system_compat(shell, cmd, also_return_output)
    445   # stack.
    446   result = _run_command(
--> 447       shell.var_expand(cmd, depth=2), clear_streamed_output=False)
    448   shell.user_ns['_exit_code'] = result.returncode
    449   if -result.returncode in _INTERRUPTED_SIGNALS:

[/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in _run_command(cmd, clear_streamed_output)
    166   if locale_encoding != _ENCODING:
    167     raise NotImplementedError(
--> 168         'A UTF-8 locale is required. Got {}'.format(locale_encoding))
    169 
    170   parent_pty, child_pty = pty.openpty()

NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968
```

Any thoughts?
Best

**Comment by huanbaoscripps** [comment] 2022-07-15 21:46
I got the same problem here today. How to save the data?

**Comment by Htomlinson14** [comment] 2022-08-19 13:35
Hi - thanks for raising this issue! Closing as this is a duplicate of https://github.com/deepmind/alphafold/issues/483

**Closed by Htomlinson14** 2022-08-19 13:35 UTC
Labels: duplicate
