### ISSUE TITLE
GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available:

### ISSUE THREAD

**Issue by KrFrandsen** [deepmind/alphafold#463] opened 2022-05-11 12:07 UTC
**trying to build the docker image for AlphaFold v2.2.0 on CentOS 7 using**:
 _docker build -f docker/Dockerfile -t alphafold ._ 

**But I fail with this message:**
_W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed._

**Could you assist me here ?**

(alphafold) [root@localhost alphafold-2.2.0]# docker build -f docker/Dockerfile -t alphafold .
Sending build context to Docker daemon  7.203MB
Step 1/18 : ARG CUDA=11.1
Step 2/18 : FROM nvidia/cuda:${CUDA}-cudnn8-runtime-ubuntu18.04
 ---> 81a7b51c961c
Step 3/18 : ARG CUDA
 ---> Using cache
 ---> 7b4ea3583467
Step 4/18 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> 821d4ba2ec1f
Step 5/18 : RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y       build-essential       cmake       cuda-command-line-tools-${CUDA/./-}       git       hmmer       kalign       tzdata       wget     && rm -rf /var/lib/apt/lists/*
 ---> Running in 131c8c2a7422
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease [1575 B]
Err:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
Get:3 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Ign:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
Get:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [833 B]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [21.1 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2747 kB]
Get:9 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Packages [73.8 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [921 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1498 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2275 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3181 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [29.8 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [954 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [12.2 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [12.9 kB]
Reading package lists...
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
The command '/bin/bash -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y       build-essential       cmake       cuda-command-line-tools-${CUDA/./-}       git       hmmer       kalign       tzdata       wget     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by ioioba** [comment] 2022-05-12 08:14
I have the same problem.
It's related to:
https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/
https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212771

Most solutions that were suggested did not work for me.

**Comment by px172** [comment] 2022-05-12 08:24
remove /etc/apt/sources.list.d/cuda.list and /etc/apt/sources.list.d/nvidia-ml.list before updating the key.

RUN rm /etc/apt/sources.list.d/cuda.list
RUN rm /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-key del 7fa2af80
RUN apt-get update && apt-get install -y --no-install-recommends wget
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb
RUN dpkg -i cuda-keyring_1.0-1_all.deb

**Comment by gretabellinzona** [comment] 2022-05-12 09:54
I got the same errors and none of the solutions suggested by nvdia-cuda worked for me.

**Comment by fbartusch** [comment] 2022-05-12 11:33
I was able to build the Docker container from the Dockerfile last week by adding this line:

```
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
```

**Comment by 0Bernhard** [comment] 2022-05-19 08:45
I have exactly the same problem. None of the suggestions above helped. Is there an update from the developers on this issue yet? 

docker build -f docker/Dockerfile -t alphafold .
Sending build context to Docker daemon  13.31MB
Step 1/18 : ARG CUDA=11.1
Step 2/18 : FROM nvidia/cuda:${CUDA}-cudnn8-runtime-ubuntu18.04
 ---> 81a7b51c961c
Step 3/18 : ARG CUDA
 ---> Using cache
 ---> a45fc778b185
Step 4/18 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> 226f7f1a04ce
Step 5/18 : RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y       build-essential       cmake       cuda-command-line-tools-${CUDA/./-}       git       hmmer       kalign       tzdata       wget     && rm -rf /var/lib/apt/lists/*
 ---> Running in 4cba039f6292
Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease [1581 B]
Err:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:7 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
Get:8 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:9 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [833 B]
Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:13 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Packages [73.8 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [966 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [29.8 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3199 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2277 kB]
Get:18 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2765 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [12.9 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [12.2 kB]
Get:21 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [932 kB]
Get:22 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [22.8 kB]
Get:23 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1503 kB]
Reading package lists...

**Comment by Augustin-Zidek** [comment] 2022-05-19 09:23
@0Bernhard Have you tried adding the following just below the `SHELL ["/bin/bash", "-c"]` line in the Dockerfile?

```bash
SHELL ["/bin/bash", "-c"]

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
```

The issue is also known to Nvidia and they will hopefully resolve it soon (this week) by releasing an updated Docker image, see https://gitlab.com/nvidia/container-images/cuda/-/issues/158 for more details.

**Comment by tcoates5** [comment] 2022-05-19 14:14
FYI, there are two PRs that fix this by running apt-key command, so you can use those until Nvidia fixes this if you want

**Comment by KrFrandsen** [comment] 2022-05-23 08:00
fbartusch's answer seemed to work for me. Thanks.

**Comment by Augustin-Zidek** [comment] 2022-06-13 11:30
Fixed in https://github.com/deepmind/alphafold/commit/55c948c1ae51a17829d7a59bd1f01eaacdf9566e by bumping the CUDA version to 11.1.1.

**Closed by Augustin-Zidek** 2022-06-13 11:30 UTC
Labels: docker, cuda
