### ISSUE TITLE
Error in Alpha Fold multimer

### ISSUE THREAD

**Issue by galshuler** [deepmind/alphafold#383] opened 2022-02-28 11:40 UTC
Hi,
I am running an Alpha fold multimer, and after a few hours of running I get the following error:
ValueError: Minimization failed after 100 attempts
Or :
ValueError: The number of positions must match the number of atoms

The error varies depending on what I define the A chain and what I define the B chain.
I would be happy to help how the error can be resolved.

Thanks in advance,
Gal

**Comment by Augustin-Zidek** [comment] 2022-02-28 11:53
Hi, 

could you try setting `run_relax=false`? This means the relaxation step will be skipped (and there might be some clashes in the output structure), but might help with your issue.

**Comment by berjeh** [comment] 2022-03-10 13:41
Dear @Augustin-Zidek does this happen for all structures or certain ones? What if I would want to see the relaxed versions?
I am also receiving the same error

**Comment by Augustin-Zidek** [comment] 2022-03-10 16:03
Relax has problems usually if there is large number of clashes in the predicted structure, so this should happen only occasionally.

With the newly release v2.2.0 the clashes in AlphaFold-Multimer should be much less frequent. Could you try updating your AlphaFold installation to see if that helps?

**Comment by avilella** [comment] 2022-03-11 10:29
I tried the v2.2.0 version today, and my code won't work with run_relax true, giving the same error as the one reported by @galshuler , but it does seem to go further with `run_relax=false`. This is on an `NVIDIA RTX A4000` with 16GB of memory.

**Comment by Aroids** [comment] 2022-07-27 13:34
Would a memory issue report a value error as opposed to a OOM error?

**Comment by Htomlinson14** [comment] 2022-08-19 13:23
Hi! In our experience the relaxation stage is less stable when use_gpu=True. This will be changed in the next release to default to False. In the meantime, this can be changed manually in the colab.

**Comment by Aroids** [comment] 2022-08-23 14:28
Will the next release (of the local installation of AlphaFold Multimer), attempt to correct the cause of the ValueError arising during relaxation? 

For large complexes GPU are seemingly required. While turning off relaxation prevents the ValueError, it also results in structures that are less suited to applications such as molecular modelling (e.g., correct charges cannot be assigned to some atoms... perhaps due to abnormal bond distances/angles).

**Comment by avilella** [comment] 2022-08-23 14:32
Hi Samuel and others,

Most of my attempts were on a 16Gb NVIDIA card, but we are considering a
24Gb to see if we can run the multimer predictions with a better parameter
set, and thus potentially obtain a better prediction.

Is there any back of the envelope calculation that could give us any
guidance as to which parameters and values we would be able to change to
accommodate a full prediction with the 24Gb card? I am not sure if the A100
40Gb cards are available for bog standard workstation machines.

**Comment by Augustin-Zidek** [comment] 2023-01-18 18:52
Is this still an issue in v2.3.1? We fixed a bunch of relax issues.

**Comment by Augustin-Zidek** [comment] 2023-02-08 15:36
Closing this issue now, feel free to re-open or open another issue if this is still a problem.

**Closed by Augustin-Zidek** 2023-02-08 15:36 UTC
Labels: relax
