### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 117: invalid continuation byte

### ISSUE THREAD

**Issue by Amit-Harita** [deepmind/alphafold#114] opened 2021-08-10 12:55 UTC
run_docker.py:193] I0810 12:44:02.365815 140477161113408 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 35.796 seconds
 run_docker.py:193] Traceback (most recent call last):
 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 302, in <module>
 run_docker.py:193] app.run(main)
 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
 run_docker.py:193] _run_main(main, args)
 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
 run_docker.py:193] sys.exit(main(argv))
 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 284, in main
 run_docker.py:193] random_seed=random_seed)
 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 128, in predict_structure
 run_docker.py:193] msa_output_dir=msa_output_dir)
 run_docker.py:193] File "/app/alphafold/alphafold/data/pipeline.py", line 134, in process
 run_docker.py:193] input_fasta_path)[0]
 run_docker.py:193] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 163, in query
 run_docker.py:193] return [self._query_chunk(input_fasta_path, self.database_path)]
 run_docker.py:193] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 140, in _query_chunk
 run_docker.py:193] 'Jackhmmer failed\nstderr:\n%s\n' % stderr.decode('utf-8'))
 run_docker.py:193] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 117: invalid continuation byte

**Comment by Augustin-Zidek** [comment] 2021-08-12 08:57
Could you try changing https://github.com/deepmind/alphafold/blob/main/alphafold/data/tools/jackhmmer.py#L131 from

```python
process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

to

```python
process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, encoding='utf-8')
```

**Comment by Amit-Harita** [comment] 2021-08-12 14:45
Thanks, Augustin, I tried by incorporating your changes, rebuilt the docker image but still getting the same error!

**Comment by Augustin-Zidek** [comment] 2021-08-12 15:10
Could you try changing:

```python
raise RuntimeError('Jackhmmer failed\nstderr:\n%s\n' % stderr.decode('utf-8'))
```

to 

```python
raise RuntimeError('Jackhmmer failed\nstderr:\n%s\n' % stderr)
```

Are you running with a non-standard sequence and/or on a system with non-utf-8 default encoding?

Note also that you have to build the Docker image, then change the code inside the Docker container.

**Comment by Augustin-Zidek** [comment] 2021-08-12 17:09
Interesting. Could you check the reported line in your uniref90.fasta?

I suggest re-downloading UniRef90, decompressing it and trying to run AlphaFold again.

**Comment by Amit-Harita** [comment] 2021-08-13 11:43
The reported line '160185303' in uniref90:  MRVKGIRRNYQHLWKWGIMLW�WGIMLPGMLMICNAKEDSWVTVYYGVPVWKEATTTLFC

There is an unknown character

**Comment by ValZapod** [comment] 2021-08-14 07:10
You should have pasted hex, since � is not the actual hex inside but a replacement character.
https://en.wikipedia.org/wiki/Specials_(Unicode_block)

But actually what happens is that above U+007F all UTF-8 bytes are not 1 byte, but more. 0xD1 in bin is  0b11010001, which means it IS NOT CONTINAUTION byte, since those start with 0b10xxxxxx.

**Comment by Amit-Harita** [comment] 2021-08-16 09:59
@ValZapod do you have any idea what should be done to avoid this?

**Comment by Amit-Harita** [comment] 2021-08-16 10:00
> Interesting. Could you check the reported line in your uniref90.fasta?
> 
> I suggest re-downloading UniRef90, decompressing it and trying to run AlphaFold again.

@Augustin-Zidek I tried after re-downloading but the issue is still unresolved

**Comment by ValZapod** [comment] 2021-08-16 10:01
> have any idea what should be done to avoid this?

Do not that bad server.

**Comment by ValZapod** [comment] 2021-08-28 16:55
Can you give a direct link to a file on that broken server somehow? I can try to report to whoever admins that.

**Comment by minsky-1** [comment] 2021-10-16 03:44
I am having the same problem, the program stops at:
       app/alphafold/alphafold/data/tools/jackhmmer.py", line 140, in _query
in spite of having made the change above.
Although it run for a longer time than before the change.
This is how the error happens,

File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 140, in _query_chunk
I1015 14:01:11.431773 140176775591744 run_docker.py:193] 'Jackhmmer failed\nstderr:\n%s\n' % stderr.decode('utf-8'))
I1015 14:01:11.431911 140176775591744 run_docker.py:193] RuntimeError: Jackhmmer failed
I1015 14:01:11.432089 140176775591744 run_docker.py:193] stderr:
I1015 14:01:11.432229 140176775591744 run_docker.py:193] 
I1015 14:01:11.432367 140176775591744 run_docker.py:193] 

I changed in /app/alphafold/alphafold/data/tools/jackhmmer.py


Any help will be very much appreciated.
Thank you in advance.

**Comment by ValZapod** [comment] 2021-10-17 09:08
> spite of having made the change above.

Those changes were not for corrupt data! Who knew server will give a corrupt information,

**Comment by Augustin-Zidek** [comment] 2022-01-20 16:59
Closing this issue as it seems to be caused by a third party server we have no control over.

> What is the minimum RAM memory on which one can ran the complete alphafold system...?

I would recommend at least 32 GB (16 GB with `--db_preset=reduced_dbs`).

**Closed by Augustin-Zidek** 2022-01-20 16:59 UTC
Labels: error report
