### ISSUE TITLE
Colab Pro: Copy to Drive fails to save the results

### ISSUE THREAD

**Issue by ExaptedAI** [deepmind/alphafold#241] opened 2021-11-10 17:39 UTC
None of the results from the completed run are saved via "Copy to Drive" option.  Only the sequence is retained.  Furthermore, the "prediction.zip", is not as comprehensive, leaving out msa files and other information.

**Comment by ConnorArkinson** [comment] 2021-11-10 18:33
Same problem, we tried moving to using Alpha-multimer locally to obtain all of this information, but can't reproduce any results locally even for easier complexes. Massive clashes with residues and results look like the data generated using old AlphaFold-monomer, but adding multiple chains with linkers.

**Comment by rjboyd00** [comment] 2021-11-24 20:31
I also am having this issue! Although it sounds like you can at least see some of the contents.

**Closed** 2022-08-19 13:49 UTC
Labels: colab
