### ISSUE TITLE
RuntimeError: HHblits failed

### ISSUE THREAD

**Issue by Lsz-20** [deepmind/alphafold#284] opened 2021-12-03 08:26 UTC
Thanks for your code,but I have met this quesiton:
![image](https://user-images.githubusercontent.com/60343452/144569718-96999bb6-77ee-4739-8ad3-04cccbd4f0cd.png)
 what's the reason about this ，and how can I solve it？
Thanks

**Comment by truatpasteurdotfr** [comment] 2021-12-06 14:30
Try to recompile HHsuite on the machine you are using to run alphafold and not the conda hhsuite version.
Possible cause: #211 (low level optimisation and incompatible cpus)

**Comment by Lsz-20** [comment] 2021-12-06 14:36
> 
ok ，thanks for your help.I'll try first if it can work well

**Comment by nick-youngblut** [comment] 2021-12-09 18:58
>Try to recompile HHsuite on the machine you are using to run alphafold and not the conda hhsuite version.
 
I tried that but I'm still getting a segfault, even when running just the hhblits job separately: 

```
/var/spool/gridengine/execd/node603/job_scripts/6891760: line 37: 71032 Segmentation fault      hhblits -i ALP2.faa -cpu 4 -oa3m /tmp/6890108.1.long.q/tmpoppa_rbx/output.a3m -o /dev/null -n 3 -e 0.001 -maxseq 1000000 -realign_max 100000 -maxfilt 100000 -min_prefilter_hits 1000 -d /ebio/abt1_share/alphafold_data/alphafold_db/v2.1.1//bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt -d /ebio/abt1_share/alphafold_data/alphafold_db/v2.1.1//uniclust30/uniclust30_2018_08/uniclust30_2018_08 
```

hhblits job output:

```
- 16:56:26.415 INFO: Searching 65983866 column state sequences.

- 16:56:28.986 INFO: Searching 15161831 column state sequences.

- 16:56:29.115 INFO: ALP2.faa is in A2M, A3M or FASTA format

- 16:56:29.116 INFO: Iteration 1

- 16:56:29.750 INFO: Prefiltering database

- 17:05:58.505 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 2494978

- 17:08:47.915 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 730232

- 17:09:06.387 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 51136

- 17:09:06.387 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 51136

- 17:09:06.387 INFO: Scoring 51136 HMMs using HMM-HMM Viterbi alignment

- 17:09:06.685 INFO: Alternative alignment: 0
```

The cluster job has plenty of memory, so that shouldn't be the issue.

**Comment by truatpasteurdotfr** [comment] 2021-12-10 08:12
If hhblits core dumps only on that specific input, I would share the test case with the hhsuite developpers for them to improve the software.

**Comment by truatpasteurdotfr** [comment] 2021-12-10 08:47
Just a quick test to make sure that hhblits does have incompatible cpu instructions:
```
$ hhblits -h
Illegal instruction (core dumped)
```

**Comment by nick-youngblut** [comment] 2021-12-10 09:23
> Just a quick test to make sure that hhblits does have incompatible cpu instructions:

I compiled hhsuite for the cluster nodes, so it's not due to incompatible cpu instructions, especially since I should then get `Illegal instruction (core dumped)` immediately when running hhblits, but instead I get the long amount of output shown above.

**Comment by AnyaP** [comment] 2021-12-10 16:24
Hi! As already mentioned on this thread, the best way to resolve this would be creating an issue in https://github.com/soedinglab/hh-suite/issues, as this sounds specific to the HHblits tool and hard to debug on our side. Thanks!

**Comment by andycowie** [comment] 2021-12-16 14:54
This may be caused by insufficient RAM – if you are using less than 32 GB RAM then upgrading your RAM to 32 GB will probably solve the issue.

Another complete workaround for this is to run with `--db_preset=reduced_dbs` as specified in the README. This uses a different tool (jackhmmer) for the genetic search. Closing the issue.

**Closed by andycowie** 2021-12-16 14:54 UTC
Labels: third-party tool
