### ISSUE TITLE
Error w multimer modeling

### ISSUE THREAD

**Issue by arashnh11** [deepmind/alphafold#227] opened 2021-11-04 01:15 UTC
Trying a sequence with two FASTA files, one after the other, getting this error after ~ 80 minutes, during msa creation. Any thoughts? 

I1103 20:24:47.638477 140257921226560 run_docker.py:222] _run_main(main, args)
I1103 20:24:47.638627 140257921226560 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I1103 20:24:47.638826 140257921226560 run_docker.py:222] sys.exit(main(argv))
I1103 20:24:47.638977 140257921226560 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 412, in main
I1103 20:24:47.639122 140257921226560 run_docker.py:222] is_prokaryote=is_prokaryote)
I1103 20:24:47.639266 140257921226560 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 169, in predict_structure
I1103 20:24:47.639411 140257921226560 run_docker.py:222] is_prokaryote=is_prokaryote)
I1103 20:24:47.639565 140257921226560 run_docker.py:222] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 282, in process
I1103 20:24:47.639721 140257921226560 run_docker.py:222] is_prokaryote=is_prokaryote,
I1103 20:24:47.639865 140257921226560 run_docker.py:222] File "/app/alphafold/alphafold/data/feature_processing.py", line 70, in pair_and_merge
I1103 20:24:47.640007 140257921226560 run_docker.py:222] chains=np_chains_list, prokaryotic=is_prokaryote)
I1103 20:24:47.640149 140257921226560 run_docker.py:222] File "/app/alphafold/alphafold/data/msa_pairing.py", line 92, in create_paired_features
I1103 20:24:47.640291 140257921226560 run_docker.py:222] chains, prokaryotic)
I1103 20:24:47.640434 140257921226560 run_docker.py:222] File "/app/alphafold/alphafold/data/msa_pairing.py", line 349, in pair_sequences
I1103 20:24:47.640576 140257921226560 run_docker.py:222] common_species.remove(b'')  # Remove target sequence species.
I1103 20:24:47.640726 140257921226560 run_docker.py:222] ValueError: list.remove(x): x not in list

**Comment by RodenLuo** [comment] 2021-11-04 03:56
Get the same error. 

The doc in the README.md is a bit confusing. It says "provide an input fasta with multiple sequence***s***," and then give `--fasta_paths=multimer1.fasta,multimer2.fasta 
  --is_prokaryote_list=true,false ` in the example command. I met the error when I put two sequences in one fasta and set `--fasta_paths=one.fasta --is_prokaryote_list=false`. I am now trying to put them into two fasta files, each with one sequence, and see what will happen.

**Comment by arashnh11** [comment] 2021-11-04 04:19
Yes, the example that is provided with mutimers would do multiple multimers
each independently. As if you launch a multimer job once, then launch
another multimer. I frankly do not find a useful use case for that. It's
just a for loop..
And I have already tried putting two sequences with two fasta files. All it
does is two monomeric simulations of each sequence.

**Comment by arashnh11** [comment] 2021-11-04 04:21
In short, two independent monomers will be predicted if you put two fasta
sequence paths.

**Comment by RodenLuo** [comment] 2021-11-04 05:53
Then it is even more confusing. But glad to know two fasta files with one sequence in each can run through. I guess then if one would like to predict a dimer, the workaround would be to put two identical sequences in one fasta and then duplicate it and feed two identical files.

**Comment by Augustin-Zidek** [comment] 2021-11-04 09:44
Hi @arashnh11 and @RodenLuo, thanks for reporting. 

Could you share the FASTA file that triggers this bug, so that we can replicate the issue and send a fix?

**Comment by RodenLuo** [comment] 2021-11-04 11:04
Hi @Augustin-Zidek Thanks. With this [spectrin_dimer.fasta.zip](https://github.com/deepmind/alphafold/files/7474218/spectrin_dimer.fasta.zip) fasta file, and the command below, I have the error. 

```bash
python3 docker/run_docker.py --fasta_paths=../af2_multimer_run/RBC_spectrin/spectrin_dimer.fasta --is_prokaryote_list=false --max_template_date=2021-11-03 --model_preset=multimer --data_dir=/home/luod/bio_tools/all_alphafold_data/
```

This fasta is just a concatenation of [P02549](https://www.uniprot.org/uniprot/P02549) and [P11277](https://www.uniprot.org/uniprot/P11277). I am on Ubuntu 18.04.6 LTS, [CUDA 11.1](https://github.com/deepmind/alphafold/issues/55#issuecomment-889914885).

**Comment by Augustin-Zidek** [comment] 2021-11-04 11:24
Thanks, we will investigate and fix as soon as possible.

**Comment by arashnh11** [comment] 2021-11-04 11:54
Hi @Augustin-Zidek thanks for checking on this. We are using TXNIP-TRX for benchmark validation. Here is the FASTA file:

>sp|P10599|THIO_HUMAN Thioredoxin OS=Homo sapiens OX=9606 GN=TXN PE=1 SV=3
MVKQIESKTAFQEALDAAGDKLVVVDFSATWCGPCKMIKPFFHSLSEKYSNVIFLEVDVD
DCQDVASECEVKCMPTFQFFKKGQKVGEFSGANKEKLEATINELV
>sp|Q9H3M7|TXNIP_HUMAN Thioredoxin-interacting protein OS=Homo sapiens OX=9606 GN=TXNIP PE=1 SV=1
MVMFKKIKSFEVVFNDPEKVYGSGEKVAGRVIVEVCEVTRVKAVRILACGVAKVLWMQGS
QQCKQTSEYLRYEDTLLLEDQPTGENEMVIMRPGNKYEYKFGFELPQGPLGTSFKGKYGC
VDYWVKAFLDRPSQPTQETKKNFEVVDLVDVNTPDLMAPVSAKKEKKVSCMFIPDGRVSV
SARIDRKGFCEGDEISIHADFENTCSRIVVPKAAIVARHTYLANGQTKVLTQKLSSVRGN
HIISGTCASWRGKSLRVQKIRPSILGCNILRVEYSLLIYVSVPGSKKVILDLPLVIGSRS
GLSSRTSSMASRTSSEMSWVDLNIPDTPEAPPCYMDVIPEDHRLESPTTPLLDDMDGSQD
SPIFMYAPEFKFMPPPTYTEVDPCILNNNVQ

Command line:

python3 /.../alphafold/docker/run_docker.py     --data_dir=/.../alphafold --output_dir=/.../alphafold/output/.../full_dbs/multimer     --fasta_paths=/.../alphafold/target/FASTA/CRDC/TXNIP-TXN_multimer.fasta     --is_prokaryote_list=false     --max_template_date=2021-10-11 --db_preset=full_dbs --model_preset=multimer

We use Docker, so the OS level shouldn't really matter... but we are CentOS 7.9 w Quadro RTX 8000 GPUs Driver 460 Cuda 11.2

As mentioned, the failure occurs deep into the modeling. Here is the structure of the output at the time of failure:
└── TXNIP-TXN_multimer
    └── msas
        ├── A
        │   ├── bfd_uniclust_hits.a3m
        │   ├── mgnify_hits.sto
        │   ├── pdb_hits.sto
        │   ├── uniprot_hits.sto
        │   └── uniref90_hits.sto
        ├── B
        │   ├── bfd_uniclust_hits.a3m
        │   ├── mgnify_hits.sto
        │   ├── pdb_hits.sto
        │   ├── uniprot_hits.sto
        │   └── uniref90_hits.sto
        └── chain_id_map.json

We checked on the --is_prokaryote_list a bit, it's sensitive to "true/false" meaning, simulation would immediately fail for other values which is good. But regardless of the boolean value, the same error appears. 

We can confirm that if we split the FASTA file and feed it into two paths with two boolean values the simulation finishes, but the results are two independent monomers.

**Comment by Augustin-Zidek** [comment] 2021-11-04 12:15
Thanks for the extra information @arashnh11. Would you be able to share `uniprot_hits.sto` for both `A` and `B` with us?

**Comment by arashnh11** [comment] 2021-11-04 12:50
@Augustin-Zidek here you go:
https://drive.google.com/drive/folders/1EYn9kYZrkgZI_7tocQC7C7HC2UzDiJXF?usp=sharing
Github doesn't let me attached either .sto or .zip. You should be able to get it above. Let me know if you need any other info

**Comment by RodenLuo** [comment] 2021-11-04 13:10
So, in my case, if I split the FASTA file into two paths as @arashnh11 mentioned, it is currently at the line below and still running. 

```
...
I1104 14:28:56.312636 22879718491968 run_docker.py:222] I1104 11:28:56.311567 140472493666880 amber_minimize.py:405] Minimizing protein, attempt 1 of 100.
I1104 14:29:01.242488 22879718491968 run_docker.py:222] I1104 11:29:01.241372 140472493666880 amber_minimize.py:69] Restraining 18173 / 38958 particles.
```

If I have P02549 and P11277 at one single path, at the error, I have the following output. 

```bash
spectrin_dimer
└── msas
    ├── A
    │   ├── bfd_uniclust_hits.a3m
    │   ├── mgnify_hits.sto
    │   ├── pdb_hits.sto
    │   ├── uniprot_hits.sto
    │   └── uniref90_hits.sto
    ├── B
    │   ├── bfd_uniclust_hits.a3m
    │   ├── mgnify_hits.sto
    │   ├── pdb_hits.sto
    │   ├── uniprot_hits.sto
    │   └── uniref90_hits.sto
    └── chain_id_map.json

3 directories, 11 files
```
`uniprot_hits.sto` for both `A` (2.1GB) and `B` (3.0GB): Google Drive [Link](https://drive.google.com/drive/folders/1l1YLw3hrMi99daFhlAu5TDKxIu3TNEEt?usp=sharing) for "AB uniprot_hits.sto for AF2_M.zip" (222.2MB)

If I have P02549 and then P11277 in one FASTA file, P11277 and then P02549 in another FASTA file, and feed both paths, it also gives the same error. The output dir structure is the same as above, and a bit surprisingly the `uniprot_hits.sto` for both `A` and `B` are also the same as the above-shared ones (same in terms of `diff`). 

I'm also on docker... 

Thanks

**Comment by Augustin-Zidek** [comment] 2021-11-04 13:14
Splitting the input fasta file into multiple files with single sequence in each will fold each file separately – we will make this clearer in the README together with the fix. Sorry about the confusion!

**Comment by Augustin-Zidek** [comment] 2021-11-04 14:36
We now understand the bug, we will submit a fix soon. The issue is that the input FASTA is not expected to contain SwissProt identifiers. 

**Simple workaround:** change the names of the sequences in the input FASTA file to be "chain_0", "chain_1", ... like this:

```
>chain_0
SEQUENCE_1_GOES_HERE
>chain_1
SEQUENCE_2_GOES_HERE
```

**Comment by RodenLuo** [comment] 2021-11-04 14:50
Great! Thanks! I would also suggest the README can reveal more clearly how to run a homo-dimer (or oligomer in general) of one sequence, and a hetero-dimer of two sequences.

**Comment by arashnh11** [comment] 2021-11-04 16:51
That works thanks @Augustin-Zidek. We have model_1 results. Will report back soon if there is an issue.

**Comment by Augustin-Zidek** [comment] 2021-11-05 10:00
Fixed in https://github.com/deepmind/alphafold/commit/c128d1aa2c21407fbe51d3cd87b85d4c5942056d.
Documentation improved in https://github.com/deepmind/alphafold/commit/be37a41d6f83e4145bd4912cbe8bf6a24af80c29.

**Closed by Augustin-Zidek** 2021-11-05 10:00 UTC
Labels: error report
