### ISSUE TITLE
hmmsearch failed: Parse failed (sequence file /path/pdb_seqres/pdb_seqres.txt): Line 1360234: illegal character 0

### ISSUE THREAD

**Issue by jsnelsonbsu** [deepmind/alphafold#569] opened 2022-08-19 22:51 UTC
Similar to #465 I am getting an error with hmmsearch when running with multimer

Full output from this command:

```
run_alphafold.sh -d $DATA_DIR -o $OUTPUT_DIR -m multimer -f ./com_triplechain.fasta -t 2021-11-01
```

```
I0805 19:28:33.717985 46912500021056 templates.py:857] Using precomputed obsolete pdbs /bsuscratch/alphafold_data/pdb_mmcif/obsolete.dat.
I0805 19:28:33.891316 46912500021056 tpu_client.py:54] Starting the local TPU driver.
I0805 19:28:33.920382 46912500021056 xla_bridge.py:212] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
I0805 19:28:34.044928 46912500021056 xla_bridge.py:212] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I0805 19:28:37.823009 46912500021056 run_alphafold.py:376] Have 25 models: ['model_1_multimer_v2_pred_0', 'model_1_multimer_v2_pred_1', 'model_1_multimer_v2_pred_2', 'model_1_multimer_v2_pred_3', 'model_1_multimer_v2_pred_4', 'model_2
_multimer_v2_pred_0', 'model_2_multimer_v2_pred_1', 'model_2_multimer_v2_pred_2', 'model_2_multimer_v2_pred_3', 'model_2_multimer_v2_pred_4', 'model_3_multimer_v2_pred_0', 'model_3_multimer_v2_pred_1', 'model_3_multimer_v2_pred_2', 'm
odel_3_multimer_v2_pred_3', 'model_3_multimer_v2_pred_4', 'model_4_multimer_v2_pred_0', 'model_4_multimer_v2_pred_1', 'model_4_multimer_v2_pred_2', 'model_4_multimer_v2_pred_3', 'model_4_multimer_v2_pred_4', 'model_5_multimer_v2_pred_
0', 'model_5_multimer_v2_pred_1', 'model_5_multimer_v2_pred_2', 'model_5_multimer_v2_pred_3', 'model_5_multimer_v2_pred_4']
I0805 19:28:37.823210 46912500021056 run_alphafold.py:393] Using random seed 86826968549806053 for the data pipeline
I0805 19:28:37.823433 46912500021056 run_alphafold.py:161] Predicting com_triplechain
I0805 19:28:37.828343 46912500021056 pipeline_multimer.py:210] Running monomer pipeline on chain A: NP_001845.3 collagen alpha-1(XI) chain isoform A preproprotein [Homo sapiens]
I0805 19:28:37.828579 46912500021056 jackhmmer.py:133] Launching subprocess "/opt/miniconda3/envs/alphafold/bin/jackhmmer -o /dev/null -A /tmp/tmpk8rj7lv_/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --
cpu 8 -N 1 /tmp/tmpohw5d8y6.fasta /bsuscratch/alphafold_data/uniref90/uniref90.fasta"
I0805 19:28:37.903680 46912500021056 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I0805 19:40:50.360106 46912500021056 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 732.456 seconds
I0805 19:41:06.558286 46912500021056 jackhmmer.py:133] Launching subprocess "/opt/miniconda3/envs/alphafold/bin/jackhmmer -o /dev/null -A /tmp/tmp24yuqeyw/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --
cpu 8 -N 1 /tmp/tmpohw5d8y6.fasta /bsuscratch/alphafold_data/mgnify/mgy_clusters_2018_12.fa"
I0805 19:41:06.636113 46912500021056 utils.py:36] Started Jackhmmer (mgy_clusters_2018_12.fa) query
I0805 19:50:41.121418 46912500021056 utils.py:40] Finished Jackhmmer (mgy_clusters_2018_12.fa) query in 574.485 seconds
I0805 19:51:11.024435 46912500021056 hmmbuild.py:121] Launching subprocess ['/opt/miniconda3/envs/alphafold/bin/hmmbuild', '--hand', '--amino', '/tmp/tmpcxqj7avx/output.hmm', '/tmp/tmpcxqj7avx/query.msa']
I0805 19:51:11.121154 46912500021056 utils.py:36] Started hmmbuild query
I0805 19:51:14.817070 46912500021056 hmmbuild.py:128] hmmbuild stdout:
# hmmbuild :: profile HMM construction from multiple sequence alignments
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# input alignment file:             /tmp/tmpcxqj7avx/query.msa
# output HMM file:                  /tmp/tmpcxqj7avx/output.hmm
# input alignment is asserted as:   protein
# model architecture construction:  hand-specified by RF annotation
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# idx name                  nseq  alen  mlen eff_nseq re/pos description
#---- -------------------- ----- ----- ----- -------- ------ -----------
1     query                 9698 10179  1806    14.95  0.590

# CPU time: 3.38u 0.29s 00:00:03.67 Elapsed: 00:00:03.67


stderr:


I0805 19:51:14.817687 46912500021056 utils.py:40] Finished hmmbuild query in 3.696 seconds
I0805 19:51:14.837767 46912500021056 hmmsearch.py:103] Launching sub-process ['/opt/miniconda3/envs/alphafold/bin/hmmsearch', '--noali', '--cpu', '8', '--F1', '0.1', '--F2', '0.1', '--F3', '0.1', '--incE', '100', '-E', '100', '--domE'
, '100', '--incdomE', '100', '-A', '/tmp/tmpkrvoumqg/output.sto', '/tmp/tmpkrvoumqg/query.hmm', '/bsuscratch/alphafold_data/pdb_seqres/pdb_seqres.txt']
I0805 19:51:14.933775 46912500021056 utils.py:36] Started hmmsearch (pdb_seqres.txt) query
I0805 19:52:02.250446 46912500021056 utils.py:40] Finished hmmsearch (pdb_seqres.txt) query in 47.316 seconds
Traceback (most recent call last):
  File "/opt/alphafold/run_alphafold.py", line 422, in <module>
    app.run(main)
  File "/opt/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/opt/alphafold/run_alphafold.py", line 398, in main
    predict_structure(
  File "/opt/alphafold/run_alphafold.py", line 172, in predict_structure
    feature_dict = data_pipeline.process(
  File "/opt/alphafold/alphafold/data/pipeline_multimer.py", line 264, in process
    chain_features = self._process_single_chain(
  File "/opt/alphafold/alphafold/data/pipeline_multimer.py", line 212, in _process_single_chain
    chain_features = self._monomer_data_pipeline.process(
  File "/opt/alphafold/alphafold/data/pipeline.py", line 185, in process
    pdb_templates_result = self.template_searcher.query(msa_for_templates)
  File "/opt/alphafold/alphafold/data/tools/hmmsearch.py", line 79, in query
    return self.query_with_hmm(hmm)
  File "/opt/alphafold/alphafold/data/tools/hmmsearch.py", line 112, in query_with_hmm
    raise RuntimeError(
RuntimeError: hmmsearch failed:
stdout:
# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  /tmp/tmpkrvoumqg/query.hmm
# target sequence database:        /bsuscratch/alphafold_data/pdb_seqres/pdb_seqres.txt
# MSA of all hits saved to file:   /tmp/tmpkrvoumqg/output.sto
# show alignments in output:       no
# sequence reporting threshold:    E-value <= 100
# domain reporting threshold:      E-value <= 100
# sequence inclusion threshold:    E-value <= 100
# domain inclusion threshold:      E-value <= 100
# MSV filter P threshold:       <= 0.1
# Vit filter P threshold:       <= 0.1
# Fwd filter P threshold:       <= 0.1
# number of worker threads:        8
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       query  [M=1806]


stderr:
Parse failed (sequence file /bsuscratch/alphafold_data/pdb_seqres/pdb_seqres.txt):
Line 1360234: illegal character 0
```

I'm not sure how to fix this.

**Comment by AlenGhzau** [comment] 2022-08-21 10:24
the same issue,do you get the way?

**Comment by shahryary** [comment] 2022-08-24 12:07
I had same issue! running Alphafold with "multimer" option need higher RAM. I was able to run multimer samples with 256 GB of RAM instead of 64 RAM that failed! - also would be better if you have higher GPU memory too.

**Comment by qisun2** [comment] 2022-08-24 13:14
I ran into the same problem. It is due to the file pdb_seqres/pdb_seqres.txt, which is a fasta file of necleotide sequences. With this awk command I can identify 4 sequences containing the character "0": awk 'NR%2==0' pdb_seqres.txt|grep 0

I used "vi" to delete the 4 sequence records, now multipler works. 

I just downloaded the latest version of pdb_seqres.txt. The problem is still there.

**Comment by yamule** [comment] 2022-08-25 12:50
I reported PDB's help desk and they said that there is an issue in their side and they will fix it.
But I don't know how it will be fixed (whether 0 will be changed to N or some other acceptable characters or not).

**Comment by koster20** [comment] 2022-09-01 11:57
You can just delete lines with those symbols.  This is NOT amino acids, and that's why alphafold can't parse it. If you delete them your program will run successful.
There is 3 or 4 lines with those molecules. 
```
>7OOS_1|Chain A|RNA (5'-R(*CP*AP*AP*AP*GP*AP*AP*AP*AP*G)-3')|synthetic construct (32630)
CAAAGAAAAG
>7OOS_2|Chain B|DNA (5'-D(*CP*TP*(RWT)P*TP*CP*TP*TP*TP*G)-3')|synthetic construct (32630)
CT05KTCTTTG
```

I think that it's bad solution, but at least something.

**Comment by tfgg** [comment] 2022-09-19 15:31
Hi, thank you for the reports. This is indeed due to pdb_seqres containing non-amino acid sequences (an error on our part). We will update the download script to use pdb_aa.fasta and make other code changes required to handle the slightly different formatting.

For now you can remove the offending lines as @koster20 commented. Apologies again.

**Comment by Augustin-Zidek** [comment] 2022-12-13 11:57
Thanks, we fixed this in the pdb_seqres download script in v2.3.0.

**Closed by Augustin-Zidek** 2022-12-13 11:57 UTC
Labels: third-party tool

**Comment by mailmrcai** [comment] 2023-12-08 07:04
The above solutions is not work for me.  I fixed this by reinstalling hh-suite;    https://github.com/soedinglab/hh-suite
