### ISSUE TITLE
simtk.openmm.OpenMMException: Particle coordinate is nan

### ISSUE THREAD

**Issue by giangpth** [deepmind/alphafold#382] opened 2022-02-24 14:46 UTC
Has anybody encountered this problem while running the prediction with some mutation of some protein? 
```
I0224 14:20:05.917235 140076864894784 run_docker.py:247] Traceback (most recent call last):
I0224 14:20:05.917589 140076864894784 run_docker.py:247] File "/app/alphafold/run_alphafold.py", line 445, in <module>
I0224 14:20:05.917792 140076864894784 run_docker.py:247] app.run(main)
I0224 14:20:05.917975 140076864894784 run_docker.py:247] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0224 14:20:05.918150 140076864894784 run_docker.py:247] _run_main(main, args)
I0224 14:20:05.918317 140076864894784 run_docker.py:247] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0224 14:20:05.918479 140076864894784 run_docker.py:247] sys.exit(main(argv))
I0224 14:20:05.918641 140076864894784 run_docker.py:247] File "/app/alphafold/run_alphafold.py", line 429, in main
I0224 14:20:05.918804 140076864894784 run_docker.py:247] is_prokaryote=is_prokaryote)
I0224 14:20:05.918967 140076864894784 run_docker.py:247] File "/app/alphafold/run_alphafold.py", line 250, in predict_structure
I0224 14:20:05.919129 140076864894784 run_docker.py:247] relaxed_pdb_str, _, _ = amber_relaxer.process(prot=unrelaxed_protein)
I0224 14:20:05.919293 140076864894784 run_docker.py:247] File "/app/alphafold/alphafold/relax/relax.py", line 66, in process
I0224 14:20:05.919457 140076864894784 run_docker.py:247] use_gpu=self._use_gpu)
I0224 14:20:05.919620 140076864894784 run_docker.py:247] File "/app/alphafold/alphafold/relax/amber_minimize.py", line 467, in run_pipeline
I0224 14:20:05.919822 140076864894784 run_docker.py:247] pdb_string = clean_protein(prot, checks=checks)
I0224 14:20:05.919986 140076864894784 run_docker.py:247] File "/app/alphafold/alphafold/relax/amber_minimize.py", line 172, in clean_protein
I0224 14:20:05.920177 140076864894784 run_docker.py:247] fixed_pdb = cleanup.fix_pdb(pdb_file, alterations_info)
I0224 14:20:05.920340 140076864894784 run_docker.py:247] File "/app/alphafold/alphafold/relax/cleanup.py", line 55, in fix_pdb
I0224 14:20:05.920501 140076864894784 run_docker.py:247] fixer.addMissingAtoms(seed=0)
I0224 14:20:05.920661 140076864894784 run_docker.py:247] File "/opt/conda/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 954, in addMissingAtoms
I0224 14:20:05.920826 140076864894784 run_docker.py:247] mm.LocalEnergyMinimizer.minimize(context)
I0224 14:20:05.920989 140076864894784 run_docker.py:247] File "/opt/conda/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 4110, in minimize
I0224 14:20:05.921152 140076864894784 run_docker.py:247] return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
I0224 14:20:05.921315 140076864894784 run_docker.py:247] simtk.openmm.OpenMMException: Particle coordinate is nan
```
If anyone knows how to solve it, please let me know.
Thank you so much.

**Comment by abridgland** [comment] 2022-03-17 16:16
Hi, that's not something I've seen. Is this something you're still seeing, and if so are you able to share the inputs and how you are running AlphaFold? Thanks!

Duplicate of: #120

**Comment by abridgland** [comment] 2022-03-17 16:17
Duplicate of #120

**Comment by willems533** [comment] 2022-07-04 06:44
Hi, I encountered a similar issue with the latest version 2.2.2:

```
Total JAX model model_1_multimer_v2_pred_0 on AFL1_tetramer predict time (includes compilation time, see --benchmark): 91712.4s
Traceback (most recent call last):
  File "/apps/gent/RHEL8/cascadelake-ib/software/AlphaFold/2.2.2-foss-2021a/bin/alphafold", line 459, in <module>
    app.run(main)
  File "/apps/gent/RHEL8/cascadelake-ib/software/jax/0.3.9-foss-2021a/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/apps/gent/RHEL8/cascadelake-ib/software/jax/0.3.9-foss-2021a/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/apps/gent/RHEL8/cascadelake-ib/software/AlphaFold/2.2.2-foss-2021a/bin/alphafold", line 441, in main
    predict_structure(
  File "/apps/gent/RHEL8/cascadelake-ib/software/AlphaFold/2.2.2-foss-2021a/bin/alphafold", line 282, in predict_structure
    relaxed_pdb_str, _, _ = amber_relaxer.process(prot=unrelaxed_protein)
  File "/apps/gent/RHEL8/cascadelake-ib/software/AlphaFold/2.2.2-foss-2021a/lib/python3.9/site-packages/alphafold/relax/relax.py", line 61, in process
    out = amber_minimize.run_pipeline(
  File "/apps/gent/RHEL8/cascadelake-ib/software/AlphaFold/2.2.2-foss-2021a/lib/python3.9/site-packages/alphafold/relax/amber_minimize.py", line 467, in run_pipeline
    pdb_string = clean_protein(prot, checks=checks)
  File "/apps/gent/RHEL8/cascadelake-ib/software/AlphaFold/2.2.2-foss-2021a/lib/python3.9/site-packages/alphafold/relax/amber_minimize.py", line 172, in clean_protein
    fixed_pdb = cleanup.fix_pdb(pdb_file, alterations_info)
  File "/apps/gent/RHEL8/cascadelake-ib/software/AlphaFold/2.2.2-foss-2021a/lib/python3.9/site-packages/alphafold/relax/cleanup.py", line 55, in fix_pdb
    fixer.addMissingAtoms(seed=0)
  File "/apps/gent/RHEL8/cascadelake-ib/software/AlphaFold/2.2.2-foss-2021a/lib/python3.9/site-packages/pdbfixer/pdbfixer.py", line 954, in addMissingAtoms
    mm.LocalEnergyMinimizer.minimize(context)
  File "/apps/gent/RHEL8/cascadelake-ib/software/AlphaFold/2.2.2-foss-2021a/lib/python3.9/site-packages/simtk/openmm/openmm.py", line 14895, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
simtk.openmm.OpenMMException: Particle coordinate is nan
```

**Comment by BastianKalcher** [comment] 2022-07-09 08:03
I have the same issue

**Closed** 2022-08-19 13:01 UTC
Labels: error report
