### ISSUE TITLE
[Colab] module 'jax' has no attribute 'xla' error

### ISSUE THREAD

**Issue by HaydenGJ** [deepmind/alphafold#814] opened 2023-08-10 00:03 UTC
Hi,

I faced an attribute error when running "5. Run AlphaFold and download prediction" part in colab.
The ipynb I used is the one given in the main readme page, and was accessed on August 9, 2023. (So I guess it's the most recent version.)
I was running with the default setting for everything (i.e. I did not adjust any code and just ran the given colab notebook with colab's T4 GPU.)

My error message is as follows:
<img width="1363" alt="image" src="https://github.com/deepmind/alphafold/assets/141883925/ecee65bc-8737-48c4-83c9-cd81e0816d71">
<img width="1327" alt="image" src="https://github.com/deepmind/alphafold/assets/141883925/e6f82e08-5e55-42a6-8485-3614b972943c">

Did anyone face this error too?
Any help would be greatly appreciated!

**Comment by YuriModeX** [comment] 2023-08-10 14:48
Having the same issue

**Comment by Htomlinson14** [comment] 2023-08-11 15:06
Thanks for raising this! Fixed in https://github.com/deepmind/alphafold/commit/7c9114c8423ac9db981d8365168464bab09b3e54

**Closed by Htomlinson14** 2023-08-11 15:06 UTC

**Comment by upagnya** [comment] 2023-08-15 12:48
Still facing the same issue.

**Comment by Htomlinson14** [comment] 2023-08-15 17:09
Can you please try restart your run time and try again?

**Comment by galcapitus** [comment] 2023-08-21 22:21
Hello, running into the same error as of 8/21/2023, tried restarting runtime without success

**Comment by Htomlinson14** [comment] 2023-08-24 12:32
I've been unable to reproduce this unfortunately. Can you share more details on how you are running this?

**Comment by ElinorWing** [comment] 2023-08-25 08:04
I am also having this issue. 

Like the original poster I am using all default settings and haven't altered any code. I get the exact same error "module 'jax' has no attribute 'xla'".

I've tried restarting multiple times.

**Comment by emilyrkang** [comment] 2023-08-25 22:28
I'm encountering this error code while using the gget tool's alphafold module. 

`AttributeError: module 'jax' has no attribute 'xla'
`

**Comment by Htomlinson14** [comment] 2023-08-29 10:21
Hi just to check -- are you running on the notebook in this repo, or on colabfold?

**Comment by ElinorWing** [comment] 2023-08-29 11:02
I am running the notebook on colabfold.

**Comment by Htomlinson14** [comment] 2023-08-29 11:35
Thanks. Both gget and colabfold are different repositories. Can you please raise this issue on there? The issue has been fixed in the notebook on this repo but they may not have updated the requirements yet

**Comment by laumiro978** [comment] 2023-09-14 12:59
I have the same problem, the error: 

AttributeError: module 'jax' has no attribute 'xla'  

appears all the time when I use ColabFold v1.5.2

**Comment by Htomlinson14** [comment] 2023-09-14 13:00
Hi can you please raise this issue on the colabfold codebase?

**Comment by sokrypton** [comment] 2023-09-15 22:50
@laumiro978 
This issue should've been fixed in colabfold long ago... make sure you are using the latest notebook.
